### PR TITLE
Add Python 3.8 to build matrix and bump build number

### PR DESCRIPTION
**Pull request by borupdaniel**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender.

**Comment by borupdaniel** [comment]
@grlee77 — do you know if I'm able to initiate an update to Python 3.8 myself, or do I need to wait for a PR to appear from @regro-cf-autotick-bot here? I've tried adding the `migrations/python38.yaml` file to my fork, but I'm not able to rerender after that.

**Comment by grlee77** [comment]
I don't know why the bot did not already make a PR here. You might try asking in https://gitter.im/conda-forge/conda-forge.github.io

I tried it locally and it wouldn't rerender here either. It does rerender if I remove the `python` entries from `recipe/conda_build_config.yaml` as well as the ``{{ python }}`` in ``meta.yaml`` (also removing the pin_compatible logic from python under the run requirements). I don't really understand what those were included for?

It looks like the build script is just copying files and doesn't actually run any typical python/pip install. If there is no compilation going on then the package could be marked as `noarch` and there should be no need to migrate across python versions.

**Comment by grlee77** [comment]
If unfamiliar, this is what I meant by `noarch`:
https://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages

**Comment by borupdaniel** [comment]
> I don't really understand what those were included for?

The python and pyqt pinnings were included so that tests for both python and qt versions would run as part of the "build", such as it is. I'm guessing this isn't really their intended use, but it worked for us at the time we set this up.

> It looks like the build script is just copying files and doesn't actually run any typical python/pip install. If there is no compilation going on then the package could be marked as `noarch` and there should be no need to migrate across python versions.

I agree (as @aganders3 had pointed out to me) that this should be `noarch`. From your link above, it looks like there's a way to avoid python 2, which was one problem I didn't know how to address before.

Do either of you know if there's a way to test on a matrix of python/qt versions if we package this as `noarch`? I suppose testing `gpi_core` as a downstream would take care of this even if I make this package noarch?

**Comment by aganders3** [comment]
I agree as a pure Python package the framework _should_ be `noarch`, but the other problem with `noarch` was the compatibility with Windows. I think there is still a PR to bring minimal Windows compatibility, but `PyFI` is still part of the framework and as far as I know it is pretty useless on Windows. Certainly all the c-based core nodes do not work on Windows at this point - we also talked about creating a "light" version of that package (pure Python nodes only) for the Windows version.

**Comment by borupdaniel** [comment]
Ah, right, I don't see a way to exclude windows without using a selector. However, per the documentation, you can achieve the same thing by requiring a package at run-time that's not available on the given architecture. Do we A) already have something that fits that description, or B) want to include `gpi_core` as a requirement, in which case there would be no windows version available?

**Comment by borupdaniel** [comment]
> noarch: python can also work with recipes that would work on a given platform except that we don’t have one of its dependencies available. If this is the case, when the install runs conda will fail with an error message describing which dependency couldn’t be found.

**Comment by aganders3** [comment]
That seems fine to me and would simplify the framework packaging. I don't love the idea the package will appear available but be unable to install, but that would work. Also it seems odd to me that the core nodes would be a dep of the framework as it's really the other way around (even if nobody will want the framework without the core nodes).

With some small changes GPI _does_ work on Windows, it's just limited. I'm not sure which is worse: having no Windows version (forcing VM or WSL use) or providing a limited one.

**Comment by borupdaniel** [comment]
> With some small changes GPI _does_ work on Windows, it's just limited. I'm not sure which is worse: having no Windows version (forcing VM or WSL use) or providing a limited one.

Reviewing your PR for windows is on my to-do list so I hope to get to it soon. I'd like to give people the option to choose (i.e., adding limited windows support doesn't mean you can't still use WSL).

In the meantime, I agree `gpi` shouldn't really depend on `gpi_core`, just intend it as a work-around for the short term.

**Comment by borupdaniel** [comment]
Moving to #13 for discussion of `noarch` packaging.

**Comment by ocefpaf** [comment]
Indeed this looks like a `noarch` package. BTW, the bot did not sent a PR probably b/c this line is quite unorthodox: https://github.com/gpilab/gpi-feedstock/blob/py38/recipe/meta.yaml#L22 and there is no dependency on Python in `run`.

**Pull request closed without merging**
