### PR TITLE
v1.1 release (qt5 compatibility)

### LINKED ISSUE #4: Recipe broken with conda 4.7.5
The most recent version of this recipe built with no errors two days ago. When I try to run a local docker build I get a test failure even when using the same recipe as before. I suspect this is related to conda 4.7.5 since it was released last night and appears to be the only minor version change in the initial environment setup. 

Possibly this shares something in common with conda-forge/staged-recipes#8623 (particularly the large number of clobber warnings with a "None" source path). @conda-forge/core if you have a moment, could you take a look and see if this is indeed related or caused by something else?

Previously, testing worked fine and the output in the test section was the following:
<details>

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
INFO:conda_build.variants:Adding in variants from /tmp/tmpmw52z2u1/info/recipe/conda_build_config.yaml
Adding in variants from /tmp/tmpmw52z2u1/info/recipe/conda_build_config.yaml
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/work  to  /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/work_moved_gpi-1.0.6-py36_1_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/gpi_1561386517571/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    ca-certificates:  2019.6.16-hecc5488_0          conda-forge
    eigen:            3.3.7-h6bb024c_1000           conda-forge
    fftw:             3.3.8-nompi_h7f3a6c3_1105     conda-forge
    fontconfig:       2.13.1-he4413a7_1000          conda-forge
    freetype:         2.10.0-he983fc9_0             conda-forge
    gpi:              1.0.6-py36_1                  local      
    h5py:             2.9.0-nompi_py36hf008753_1102 conda-forge
    hdf5:             1.10.4-nompi_h3c11f04_1106    conda-forge
    icu:              58.2-hf484d3e_1000            conda-forge
    jpeg:             9c-h14c3975_1001              conda-forge
    libblas:          3.8.0-7_openblas              conda-forge
    libcblas:         3.8.0-7_openblas              conda-forge
    libffi:           3.2.1-he1b5a44_1006           conda-forge
    libgcc-ng:        9.1.0-hdf63c60_0              defaults   
    libgfortran-ng:   7.3.0-hdf63c60_0              defaults   
    libiconv:         1.15-h516909a_1005            conda-forge
    liblapack:        3.8.0-7_openblas              conda-forge
    libpng:           1.6.37-hed695b0_0             conda-forge
    libstdcxx-ng:     9.1.0-hdf63c60_0              defaults   
    libtiff:          4.0.10-h57b8799_1003          conda-forge
    libuuid:          2.32.1-h14c3975_1000          conda-forge
    libxcb:           1.13-h14c3975_1002            conda-forge
    libxml2:          2.9.9-h13577e0_0              conda-forge
    lz4-c:            1.8.3-he1b5a44_1001           conda-forge
    ncurses:          6.1-hf484d3e_1002             conda-forge
    numpy:            1.16.4-py36h95a1406_0         conda-forge
    olefile:          0.46-py_0                     conda-forge
    openblas:         0.3.5-h9ac9557_1001           conda-forge
    openssl:          1.1.1b-h14c3975_1             conda-forge
    pillow:           6.0.0-py36he7afcd5_0          conda-forge
    psutil:           5.6.3-py36h516909a_0          conda-forge
    pthread-stubs:    0.4-h14c3975_1001             conda-forge
    pyopengl:         3.1.3b2-py_1                  conda-forge
    pyqt:             4.11.4-py36_3                 conda-forge
    python:           3.6.7-h381d211_1004           conda-forge
    qimage2ndarray:   1.7-py_0                      conda-forge
    qt:               4.8.7-2                       defaults   
    readline:         7.0-hf8c457e_1001             conda-forge
    sip:              4.18-py36_1                   conda-forge
    six:              1.12.0-py36_1000              conda-forge
    sqlite:           3.28.0-h8b20d00_0             conda-forge
    tk:               8.6.9-hed695b0_1002           conda-forge
    xorg-kbproto:     1.0.7-h14c3975_1002           conda-forge
    xorg-libice:      1.0.9-h516909a_1004           conda-forge
    xorg-libsm:       1.2.3-h84519dc_1000           conda-forge
    xorg-libx11:      1.6.7-h14c3975_1000           conda-forge
    xorg-libxau:      1.0.9-h14c3975_0              conda-forge
    xorg-libxdmcp:    1.1.3-h516909a_0              conda-forge
    xorg-libxrender:  0.9.10-h516909a_1002          conda-forge
    xorg-renderproto: 0.11.1-h14c3975_1002          conda-forge
    xorg-xproto:      7.0.31-h14c3975_1007          conda-forge
    xz:               5.2.4-h14c3975_1001           conda-forge
    zlib:             1.2.11-h14c3975_1004          conda-forge
    zstd:             1.4.0-h3b9ef0a_0              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/gpi_1561386517571/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/gpi_1561386517571/test_tmp
import: 'gpi'
GPI 1.0.6 (2019-06-24)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

import: 'gpi'
+ DISPLAY=localhost:1.0
+ xvfb-run -a bash -c 'gpi --help'
GPI 1.0.6 (2019-06-24)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Usage: gpi [options]

Options:
  -h, --help            show this help message and exit
  --config              GPI will read the User ENV and config file and dump
                        the parsed info to stdout.
  --log=LOGLEVEL        Change the output level of the logger: debug, info,
                        node, warn, error, and critical
  --nogui               causes GPI to run without a GUI for scripting.
                        Requires a network file.  The --script option is
                        implied.
  --script              causes GPI to terminate after the supplied network is
                        finished executing.  Requires a network file.
  -s STRING, --string=STRING
                        passes a string arg to a String-node by label.
                        Handles multiple args.  Syntax: -s
                        <label1>:<string/path> -s <label2>:<string/path>.
  --specs               GPI will create a platform specs file and exit.
  --defines             Show some internally used defines, such as temp
                        directory paths.
  --nosplash            Skip the splash screen.
+ exit 0

Resource usage statistics from testing gpi:
   Process count: 5
   CPU time: unavailable
   Memory: 32.7M
   Disk usage: 20B
   Time elapsed: 0:00:04.1

TEST END: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
```
</details>

Now I get the following output, which includes a large number of clobber warnings (I've removed most of them for space) and ends with a failed import of qtWebKit.

Full output:
<details> 

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/gpi-1.0.6-py36_1.tar.bz2
Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
INFO conda_build.variants:_combine_spec_dictionaries(189): Adding in variants from /tmp/tmpt6t0ys3n/info/recipe/conda_build_config.yaml
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/work  to  /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/work_moved_gpi-1.0.6-py36_1_linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    ca-certificates:  2019.6.16-hecc5488_0          conda-forge
    cairo:            1.14.6-4                      conda-forge
    eigen:            3.3.7-h6bb024c_1000           conda-forge
    expat:            2.2.5-he1b5a44_1003           conda-forge
    fftw:             3.3.8-nompi_h7f3a6c3_1105     conda-forge
    fontconfig:       2.12.1-4                      conda-forge
    freetype:         2.7-1                         conda-forge
    gettext:          0.19.8.1-hc5be6a0_1002        conda-forge
    glib:             2.51.4-0                      conda-forge
    gpi:              1.0.6-py36_1                  local      
    graphite2:        1.3.13-hf484d3e_1000          conda-forge
    h5py:             2.9.0-nompi_py36hf008753_1102 conda-forge
    harfbuzz:         1.4.3-0                       conda-forge
    hdf5:             1.10.4-nompi_h3c11f04_1106    conda-forge
    icu:              58.2-hf484d3e_1000            conda-forge
    jpeg:             9c-h14c3975_1001              conda-forge
    libblas:          3.8.0-7_openblas              conda-forge
    libcblas:         3.8.0-7_openblas              conda-forge
    libffi:           3.2.1-he1b5a44_1006           conda-forge
    libgcc-ng:        9.1.0-hdf63c60_0              defaults   
    libgfortran-ng:   7.3.0-hdf63c60_0              defaults   
    libiconv:         1.15-h516909a_1005            conda-forge
    liblapack:        3.8.0-7_openblas              conda-forge
    libpng:           1.6.37-hed695b0_0             conda-forge
    libstdcxx-ng:     9.1.0-hdf63c60_0              defaults   
    libtiff:          4.0.10-h57b8799_1003          conda-forge
    libuuid:          2.32.1-h14c3975_1000          conda-forge
    libxcb:           1.13-h14c3975_1002            conda-forge
    libxml2:          2.9.9-h13577e0_0              conda-forge
    lz4-c:            1.8.3-he1b5a44_1001           conda-forge
    ncurses:          6.1-hf484d3e_1002             conda-forge
    numpy:            1.16.4-py36h95a1406_0         conda-forge
    olefile:          0.46-py_0                     conda-forge
    openblas:         0.3.5-h9ac9557_1001           conda-forge
    openssl:          1.0.2r-h14c3975_0             conda-forge
    pango:            1.40.4-0                      conda-forge
    pcre:             8.41-hf484d3e_1003            conda-forge
    pillow:           4.2.1-py36_0                  conda-forge
    pixman:           0.34.0-h14c3975_1003          conda-forge
    psutil:           5.6.3-py36h516909a_0          conda-forge
    pthread-stubs:    0.4-h14c3975_1001             conda-forge
    pyopengl:         3.1.3b2-py_1                  conda-forge
    pyqt:             4.11.4-py36_3                 conda-forge
    python:           3.6.7-hd21baee_1002           conda-forge
    qimage2ndarray:   1.7-py_0                      conda-forge
    qt:               4.8.7-ha8c56c7_9              conda-forge
    readline:         7.0-hf8c457e_1001             conda-forge
    sip:              4.18-py36_1                   conda-forge
    six:              1.12.0-py36_1000              conda-forge
    sqlite:           3.28.0-h8b20d00_0             conda-forge
    tk:               8.6.9-hed695b0_1002           conda-forge
    xorg-kbproto:     1.0.7-h14c3975_1002           conda-forge
    xorg-libice:      1.0.9-h516909a_1004           conda-forge
    xorg-libsm:       1.2.3-h84519dc_1000           conda-forge
    xorg-libx11:      1.6.7-h14c3975_1000           conda-forge
    xorg-libxau:      1.0.9-h14c3975_0              conda-forge
    xorg-libxdmcp:    1.1.3-h516909a_0              conda-forge
    xorg-libxext:     1.3.4-h516909a_0              conda-forge
    xorg-libxrender:  0.9.10-h516909a_1002          conda-forge
    xorg-libxt:       1.2.0-h516909a_0              conda-forge
    xorg-renderproto: 0.11.1-h14c3975_1002          conda-forge
    xorg-xextproto:   7.3.0-h14c3975_1002           conda-forge
    xorg-xproto:      7.0.31-h14c3975_1007          conda-forge
    xz:               5.2.4-h14c3975_1001           conda-forge
    zlib:             1.2.11-h14c3975_1004          conda-forge
    zstd:             1.4.0-h3b9ef0a_0              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... 
ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/2/2621a
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/2/2621a




ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/e/eterm
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/e/eterm




ClobberWarning: Conda was asked to clobber an existing path.
  source path: /opt/conda/pkgs/ncurses-6.1-hf484d3e_1002/share/terminfo/e/eterm-color
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/terminfo/e/eterm-color

[etc. etc.]

ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/raw/__pycache__/__init__.cpython-36.pyc




ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/__pycache__/version.cpython-36.pyc




ClobberWarning: Conda was asked to clobber an existing path.
  source path: None
  target path: /home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/OpenGL/__pycache__/wrapper.cpython-36.pyc



done
export PREFIX=/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/test_tmp
import: 'gpi'
GPI 1.0.6 (2019-06-26)  Copyright (C) 2014 Dignity Health
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/test_tmp/run_test.py", line 2, in <module>
    import gpi
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/__init__.py", line 91, in <module>
    from .widgets import *
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/widgets.py", line 34, in <module>
    QtWebKit = Qimport("QtWebKit")
  File "/home/conda/feedstock_root/build_artifacts/gpi_1561581965783/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.6/site-packages/gpi/qtapi.py", line 48, in import_module
    p = __import__('PyQt4', globals(), locals(), [moduleName], 0)
ImportError: libQtWebKit.so.4: cannot open shared object file: No such file or directory
Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2200): Tests failed for gpi-1.0.6-py36_1.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: gpi-1.0.6-py36_1.tar.bz2
```
</details>

Here's a diff of the packages installed during testing. Left is the current (breaking) version and right is the output from Azure earlier this week.

image

### PR DESCRIPTION
**Pull request by borupdaniel**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #4 

TODO
* [x] Merge the qt5 compatible branch to master and tag it as normal release in gpilab/framework
* [ ] Merge the qt5 compatible branch in gpilab/core-nodes
* [ ] Create a similar conda-forge release for gpi-core-nodes so that compatible versions are ready at the same time.

### CODE REVIEW

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by borupdaniel** [comment]
@aganders3 I'm pretty sure this works now, but I'm still not sure why the xorg/x11 related things are necessary in the test and yum_requirements.txt. I'm reading and it seems like qt requires x11 on linux systems, do you know if this is the case? If so, I'm not sure why they wouldn't be added by qt when the runtime environment is solved.

**Comment by borupdaniel** [comment]
I'm going to sum up the various things that break if make changes to the recipe:

Without gtk2 in `yum_requirements.txt`:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
```

Without making `gpi --help` an xvfb command in the test section of `meta.yaml`:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-conda'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by aganders3** [comment]
Do you want to enable building against qt5 at the same time?

**Comment by borupdaniel** [comment]
> Do you want to enable building against qt5 at the same time?

Right now it tests against the latest qt, which I think is 5.9.7. It would be great if I could just tell the recipe to test against a few versions of qt within the same build, but I'm not sure that's possible; I think it will have to be a build matrix. I'll give it a try that way and see what happens!

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by borupdaniel** [comment]
So it looks like the following setups will work:

- OSX
  - Working: Any pyqt5 with any python
  - Breaking: pyqt4 (due to unsatisfiable dependency on qt=4.8, which is only available from pkgs/free).
- Linux
  - Working: pyqt5.9
  - Working: pyqt4.11 with python 3.6
  - Breaking: pyqt5.6 (due to "xcb" issue discussed previously)
  - Breaking: pyqt4.11 with python 3.7

**Comment by aganders3** [comment]
That's great, thanks for all your work on this @borupdaniel!

I don't know the etiquette here - it seems wrong to just leave builds failing, but at the same time I kind of like building all the combos that work. Maybe I need to let go of that and just go with known-working dependency versions until we have better (any?) test coverage.

I guess we're out of luck on maintaining Qt4 support for macOS in any case if we're using conda-forge. Maybe we should take this opportunity to drop official support for Qt4 and try to stay on [supported releases](https://en.wikipedia.org/wiki/Qt_version_history#Qt_5) of Qt5 going forward. Anyone who really wants/needs things to work with Qt4 can probably install from source.

**Comment by aganders3** [comment]
Also just a note that the macOS deployment target for Qt on conda-forge is 10.12, so we may be inadvertently dropping support for 10.9-10.11 for the official package here.

**Comment by borupdaniel** [comment]
> Also just a note that the macOS deployment target for Qt on conda-forge is 10.12, so we may be inadvertently dropping support for 10.9-10.11 for the official package here.

Where are you seeing this? From the build log it looks like it's still targeting 10.9 to me:

```
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
macos_machine:
- x86_64-apple-darwin13.4.0
macos_min_version:
- '10.9'
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
pyqt:
- '5.6'
python:
- '3.6'

CONDA_BUILD_SYSROOT:
- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk

CI:
- azure
```

(from "configure conda and conda-build" [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=48963&view=logs) )

**Comment by borupdaniel** [comment]
Oh, I see, qt itself is being built with 10.12 as the target. Ours is testing successfully, but the build machine is 10.13, so I'm not sure what significance of the target=10.9 is in our case?

**Comment by aganders3** [comment]
The target doesn't have to match the build machine, so you can build for
10.9 on a 10.14 machine for example. I don't know specifically what is
lost/gained in each target bump. In any case I'm not really concerned about
support for older versions. I think you need a pretty old Mac (like a 2009
or earlier) to lose support for 10.12.

**Comment by borupdaniel** [comment]
In that case I'll bump our deployment target to 10.12 as well. In the release notes we can mention that older versions may still work but we're not guaranteeing any support there.

**Comment by borupdaniel** [comment]
I agree that we can perhaps just drop qt4 for our own sanity. The breaking build with qt5.6 on Linux seems strange though — I had this "xcb" issue earlier and solved it with yum-requirements, so I'm guessing there's a way to fix it with those again.

Edit: For what it's worth we _do_ have test coverage, and that's what's causing the failures here. It's pretty minimal, just trying to run `import gpi` within python and then `gpi --help`, but it seems good enough for now. Once the core nodes are built, I'll add that as a downstream dependency so any change we make in the framework also causes core-nodes to test itself against the new version.

**Comment by borupdaniel** [comment]
Is there an easy way to see what the deployment targets are for the packages we're linking against? I'm just thinking ahead on how to keep up to speed on upstream changes going forward.

**Comment by aganders3** [comment]
I noticed it for the Qt recipe here:
https://github.com/conda-forge/qt-feedstock/blob/master/recipe/conda_build_config.yaml

I don't know anything about that `xcb` issue but a quick google suggests it
does seem like something that may need to be fixed by system level
dependencies.

**Comment by borupdaniel** [comment]
I tried adding those libraries back with no success. I think the problem is that it's grabbing a newer qt5.6 from defaults rather than conda-forge, so I'm going to try the strict channel dependencies that were suggested earlier.

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

**Comment by borupdaniel** [comment]
I'm not sure if people will run into trouble installing on linux with qt5.6 — if so they'll also need to set strict channel priorities on their end. Alternately, I can just specify qt5.6 only with osx in the build matrix. Other than that choice, I think this is ready to go.

**Comment by borupdaniel** [comment]
@conda-forge-admin, please rerender

(just want to see if I still get the complaint from earlier)

**Comment by borupdaniel** [comment]
I'm going to go ahead and merge this, and move on to the core nodes PR. If the qt5.6 build proves problematic (I have no idea why it would), we can always ask to have it moved to the `broken` label so it won't show up by default.

**Comment by aganders3** [comment]
> I'm not sure if people will run into trouble installing on linux with qt5.6 — if so they'll also need to set strict channel priorities on their end.

We can probably set this in GPI_Install_Latest.sh if needed.

> Revert last commit, gtk2 still needed for qt5.9, apparently.

This is weird to me. Maybe installing gtk2 installs some other dependency (x-related?) we need? Anyway, I'm OK with moving on if it's working. Like you said we can mark items as `broken` if needed.

**Comment by borupdaniel** [comment]
Yeah, I think the gtk2 thing is something x-related. I went ahead and merged, and things worked, but didn't quite behave as expected. We ended up with 4 packages instead of 8 as the pyqt version wasn't included in the package name. So, the packages that are up have a random "pyqt=5.x" dependency based on the order the builds finished. I started #7 to figure out how to fix that in a new build.

**Pull request merged**
